# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - releases/*
  - dev
jobs:
  - job: build_packer
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          sudo apt-get install zip
          zip -r functions.zip azure_functions.csproj HttpFunction.cs
        displayName: 'install zip and zip files'
      - task: CopyFiles@1
        inputs:
          contents: |
            functions.zip
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: drop